### ISSUE TITLE
type cannot be converted to 'bool'

### ISSUE THREAD

**Issue by Kizoky** [sashi0034/angel-lsp#13]
![image](https://github.com/user-attachments/assets/c7a4d72d-1ac5-4714-95c3-b2213bf784a4)

Encapsulating the last check like
```
if ( !bWanted && ( pToucher.GetWanted() <= 0) )
```
will make the error go away

This also happens with strings apparently:
![image](https://github.com/user-attachments/assets/6f5f377a-e3ac-48f1-a1d6-ad1db8bfa1f8)

**Comment by sashi0034** [comment]
Sure, thanks for the report.
