### ISSUE TITLE
A way to make multiple files see each other.

### ISSUE THREAD

**Issue by MineBill** [sashi0034/angel-lsp#19]
Let me elaborate.

Currently, in my setup, i have a single `Scripts` folder where all of the scripts are placed and i recursively add them to a single `Game` module using `AddSectionFromFile` from `CScriptBuiler`. This means that all the classes/functions in the `Scripts` folder can see each other but the LSP does not.

I understand that different projects might use a completely different setup, so i was wondering if it's possible to inform the LSP that i want this kind of behavior.

I assume that the LSP currently looks for a `as.predefined` file as a `root` to figure out what completions to provide to what files, so maybe some kind of LSP project file could work? I understand that would complicate things much more so i would also be happy with a global option for the LSP.

As always, thank you for your work!

**Comment by sashi0034** [comment]
I see, thanks for your feedback! I understand that you are using behavior similar to languages like C# or Java.

I will consider implementing this feature and adding an option in the VSCode user settings to "implicitly include each other in project files".

**Comment by sashi0034** [comment]
![image](https://github.com/user-attachments/assets/b28c438d-9d97-4290-85eb-8630be4ae503)

I have implemented this configuration and it seems to work now. Please let us know if you have any further problems!
