### ISSUE TITLE
Operator overload for registered classes (in as.predefined) breaks *randomly*, *sometimes*.

### ISSUE THREAD

**Issue by MineBill** [sashi0034/angel-lsp#22]
I've tried to narrow down the problem but i couldn't easily replicate it using simple cases. As such, i will upload my `as.predefined`, `Script.as` and `Test.as` files where the problem occurs.
[Test.as.txt](https://github.com/user-attachments/files/16439951/Test.as.txt)
[Script.as.txt](https://github.com/user-attachments/files/16439952/Script.as.txt)
[as.predefined.txt](https://github.com/user-attachments/files/16439953/as.predefined.txt)
(I have added the .txt extension to keep GitHub happy).

The problem occurs in the `Test.as` file.

After opening vscode, sometimes there are no complaints but after some typing and/or saving the file a couple of times, these errors appear:
![image](https://github.com/user-attachments/assets/789127ed-f3b8-42d3-9b8c-45fb136cbe5e)
![image](https://github.com/user-attachments/assets/7c1e0835-02a2-47e1-ac0f-2f49cd0bb85b)

All of this code compiles and work as expected.

**Comment by sashi0034** [comment]
Thank you for reporting this.
I understand that this issue is related to the include feature. I will be going on an extended vacation in a few weeks, during which I plan to look into this and other bugs for a possible fix.
