### ISSUE TITLE
Support for function signature help

### ISSUE THREAD

**Issue by suprstefan** [sashi0034/angel-lsp#30]
This project seems very close to what I'm looking for but when I gave it a go I noticed that the behavior for function signature help (i.e. the popup that shows you the function arguments) isn't there. When I call a function I just get the symbol completion:
![angel-lsp](https://github.com/user-attachments/assets/71a08840-f5c0-4340-b4cb-2a59d21f7809)

If I try the same in Unreal AngelScript I get this:
![angel-hl](https://github.com/user-attachments/assets/46deaa61-c6b7-442c-8a07-d5c4b7141680)

I had a quick poke around in the code but since the extension doesn't register the onSignatureHelp-callback I assume it hasn't been implemented yet?

**Comment by sashi0034** [comment]
Thank you for your interest in this project.
You're right about the onSignatureHelp callback not being implemented yet. 
I wasn't aware of that callback myself, so thanks for pointing that out.
