### ISSUE TITLE
No completions when using types outside of the namespace they are defined in.

### ISSUE THREAD

**Issue by MineBill** [sashi0034/angel-lsp#6]
```angelscript
namespace Game {
    class Player {

        string GetName() {
            return "Name";
        }
    }

    void Test() {
        Player p;
    }
}
```
Accessing the player variable inside the `Game::Test` function, correctly offers the `GetName` method for completion:
![image](https://github.com/sashi0034/angel-lsp/assets/30367251/1594f3eb-60f0-44d7-b0c0-c607e71b42f1)

However, when using the `Game::Player` type outside the `Game` namespace, no completions are offered:
![image](https://github.com/sashi0034/angel-lsp/assets/30367251/3902179d-b5b7-4a13-ae61-5d3122c80204)
*This completion pop-up was forced open by pressing `Ctrl+Space`. Normally, nothing appears, which might not have been immediately apparent in the screenshot.*

**Comment by sashi0034** [comment]
Oh, thank you for the report.
